
export const ALL_CHAT_REQUEST = "ALL_CHAT_REQUEST";
export const ALL_CHAT_SUCCESS = "ALL_CHAT_SUCCESS";
export const ALL_CHAT_FAIL = "ALL_CHAT_FAIL";

export const NEW_CHAT_REQUEST = "NEW_CHAT_REQUEST";
export const NEW_CHAT_SUCCESS = "NEW_CHAT_SUCCESS";
export const NEW_CHAT_RESET = "NEW_CHAT_RESET";
export const NEW_CHAT_FAIL = "NEW_CHAT_FAIL";

export const ACCESS_CHAT_REQUEST = 'ACCESS_CHAT_REQUEST';
export const ACCESS_CHAT_SUCCESS = 'ACCESS_CHAT_SUCCESS';
export const ACCESS_CHAT_FAIL = 'ACCESS_CHAT_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";