export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";

export const SHOW_HOMEPOSTS_REQUEST = "SHOW_HOMEPOSTS_REQUEST";
export const SHOW_HOMEPOSTS_SUCCESS = "SHOW_HOMEPOSTS_SUCCESS";
export const SHOW_HOMEPOSTS_FAIL = "SHOW_HOMEPOSTS_FAIL";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const LIKE_UNLIKE_REQUEST = "LIKE_UNLIKE_REQUEST";
export const LIKE_UNLIKE_SUCCESS = "LIKE_UNLIKE_SUCCESS";
export const LIKE_UNLIKE_FAIL = "LIKE_UNLIKE_FAIL";

export const SAVETOGGLE_POST_REQUEST = "SAVETOGGLE_POST_REQUEST";
export const SAVETOGGLE_POST_SUCCESS = "SAVETOGGLE_POST_SUCCESS";
export const SAVETOGGLE_POST_FAIL = "SAVETOGGLE_POST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
